定存利率: 1.5

預期本益比: 15
預期股價淨值比: 3

預期資產報酬率: 0.1

預期殖利率: 3
預期殖利率_連續N年發放: 5

自由現金流_連續N年為正: 3

資產負債表頭:
  - code
  - ts
  - created_ts
  - updated_ts
  - 普通股股本
  - 特別股股本
  - 股本合計
  - 資產總計
  - 流動資產合計
  - 非流動資產合計
  - 負債及權益總計
  - 負債總計
  - 流動負債合計
  - 非流動負債合計
  - 權益總額
  - 歸屬於母公司業主之權益合計
  - 現金及約當現金
  - 母公司暨子公司所持有之母公司庫藏股股數（單位：股）
  - 保留盈餘合計
  - 資本公積合計
  - 其他非流動資產
  - 不動產、廠房及設備
  - 預收股款（權益項下）之約當發行股數
  - 其他應付款
  - 其他流動負債
  - 應付帳款
  - 應收帳款淨額
  - 其他權益合計
  - 使用權資產
  - 存貨
  - 未分配盈餘（或待彌補虧損）

現金流量表頭:
  - code
  - ts
  - created_ts
  - updated_ts
  - 投資活動之淨現金流入（流出）
  - 營業活動之淨現金流入（流出）
  - 籌資活動之淨現金流入（流出）
  - 資產負債表帳列之現金及約當現金
  - 繼續營業單位稅前淨利（淨損）
  - 期末現金及約當現金餘額
  - 本期現金及約當現金增加（減少）數
  - 本期稅前淨利（淨損）
  - 調整項目合計
  - 營運產生之現金流入（流出）
  - 期初現金及約當現金餘額
  - 與營業活動相關之資產及負債之淨變動合計
  - 與營業活動相關之負債之淨變動合計
  - 與營業活動相關之資產之淨變動合計
  - 收益費損項目合計
  - 折舊費用
  - 收取之利息
  - 利息收入
  - 利息費用
  - 支付之利息
  - 取得不動產、廠房及設備
  - 應收帳款（增加）減少
  - 退還（支付）之所得稅
  - 應付帳款增加（減少）
  - 其他應付款增加（減少）

損益表頭:
  - code
  - ts
  - created_ts
  - updated_ts
  - 基本每股盈餘合計
  - 本期淨利（淨損）
  - 營業收入合計
  - 營業成本合計
  - 營業毛利（毛損）
  - 營業毛利（毛損）淨額
  - 營業費用合計
  - 營業外收入及支出合計
  - 繼續營業單位稅前淨利（淨損）
  - 營業利益（損失）
  - 本期綜合損益總額
  - 繼續營業單位本期淨利（淨損）
  - 繼續營業單位淨利（淨損）
  - 停業單位淨利（淨損）
  - 共同控制下前手權益（淨利／損）
  - 本期稅前淨利（淨損）
  - 本期稅後淨利（淨損）
  - 繼續營業單位本期稅後淨利（淨損）
  - 本期稅後淨利（損）歸屬於母公司業主
  - 本期稅後淨利（損）歸屬於非控制權益
  - 繼續營業單位稅後淨利（淨損）
  - 本期稅後淨利（損）歸屬於共同控制下前手權益
  - 其他租賃淨利益（損失）
  - 非控制權益（淨利／損）
  - 營業利益（損失）
  - 其他利益及損失淨額
  - 財務成本淨額
  - 所得稅費用（利益）合計
  - 管理費用
  - 其他收入合計
  - 推銷費用
  - 其他綜合損益（淨額）
  - 稀釋每股盈餘合計
  - 母公司業主（淨利／損）
  - 母公司業主（綜合損益）
  - 後續可能重分類至損益之項目總額
  - 國外營運機構財務報表換算之兌換差額
  - 研究發展費用
  - 利息收入合計

累計損益表頭:
  - code
  - ts
  - created_ts
  - updated_ts
  - 累計基本每股盈餘合計
  - 累計本期淨利（淨損）
  - 累計營業收入合計
  - 累計營業成本合計
  - 累計營業毛利（毛損）
  - 累計營業毛利（毛損）淨額
  - 累計營業費用合計
  - 累計營業外收入及支出合計
  - 累計繼續營業單位稅前淨利（淨損）
  - 累計本期綜合損益總額
  - 累計繼續營業單位本期淨利（淨損）
  - 累計營業利益（損失）
  - 累計其他利益及損失淨額
  - 累計財務成本淨額
  - 累計所得稅費用（利益）合計
  - 累計管理費用
  - 累計其他收入合計
  - 累計推銷費用
  - 累計其他綜合損益（淨額）
  - 累計稀釋每股盈餘合計
  - 累計母公司業主（淨利／損）
  - 累計母公司業主（綜合損益）
  - 累計後續可能重分類至損益之項目總額
  - 累計國外營運機構財務報表換算之兌換差額
  - 累計研究發展費用
  - 累計利息收入合計
